// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLO7gBHXt1qL2IsILDxzUcR2B_eaM27M',
    appId: '1:680271642328:web:b4cb239851e865fc72a1ad',
    messagingSenderId: '680271642328',
    projectId: 'storeappz',
    authDomain: 'storeappz.firebaseapp.com',
    storageBucket: 'storeappz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakYU2NjrFFS4JvyUX4xgV74FH8swg1Io',
    appId: '1:680271642328:android:27a693685cdc525f72a1ad',
    messagingSenderId: '680271642328',
    projectId: 'storeappz',
    storageBucket: 'storeappz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKTDAgdPE5elpjXMPdbOL2BVrzSFrwiI',
    appId: '1:680271642328:ios:af66f164c8db9cc572a1ad',
    messagingSenderId: '680271642328',
    projectId: 'storeappz',
    storageBucket: 'storeappz.appspot.com',
    iosClientId:
        '680271642328-u71agoaraof52btdfbnl8f2a823pcigr.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
